[build]
publish = "public"
command = "hugo --cleanDestinationDir -D -E -F --gc --minify --cacheDir /tmp --verbose"

[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18.14.0"

[context.split1]
command = "hugo --gc --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.110.0"

[context.deploy-preview]
command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.110.0"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.110.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
  	Access-Control-Allow-Origin = "https://cybersentinels.org" 
	Cache-Control = "Public, no-transform, max-age=31536000"
	#The `Expect-CT` header is deprecated and will be removed. Chrome requires Certificate Transparency for all publicly trusted certificates issued after April 30, 2018.
	#Expect-Ct = "enforce, max-age=2592000, report-uri='https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct'"
	#Feature-Policy = "microphone 'none'; geolocation 'none'; accelerometer 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; gyroscope 'none'; magnetometer 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; publickey-credentials-get 'none'; usb 'none'; xr-spatial-tracking 'none'"
	Permissions-Policy = "sync-xhr=(self), accelerometer=(), camera=(), display-capture=(), geolocation=(), microphone=(), midi=(), payment=(), usb=(), gyroscope=(), magnetometer=(), screen-wake-lock=(), xr-spatial-tracking=()"
	Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
	Upgrade-Insecure-Requests = "1"
	Referrer-Policy	= "strict-origin"
	X-DNS-Prefetch-Control = "off"
	X-Content-Type-Options = "nosniff"
	X-Frame-Options	= "DENY"
	#X-Robots-Tag  = "noindex, nofollow, noarchive, notranslate, nosnippet, unavailable_after: 2020-09-21"
	X-Robots-Tag  = "index, follow, notranslate, max-snippet:60, max-image-preview:large"
	X-Xss-Protection = "1; mode=block"
	Content-Security-Policy = "default-src 'self' https://cybersentinels.org https://*.cloudfront.net https://ajax.cloudflare.com https://raw.githubusercontent.com 'unsafe-inline' https: data:; script-src 'self' https://cybersentinels.org https://*.cloudfront.net https://ajax.cloudflare.com https://raw.githubusercontent.com https://ws-na.amazon-adsystem.com https://*.googlesyndication.com https://www.google-analytics.com/ https://cdn.ampproject.org https://cdn.jsdelivr.net https://*.gstatic.com https://googleads.g.doubleclick.net https://tpc.googlesyndication.com https://googletagservices.com 'unsafe-inline' https: data:; font-src 'self' data: https: https://fonts.gstatic.com https://*.cloudfront.net https://cybersentinels.org; object-src 'none'; img-src 'self' data: https: https://*.cloudfront.net https://raw.githubusercontent.com; frame-src 'self' https: data: https://googleads.g.doubleclick.net https://ws-na.amazon-adsystem.com; upgrade-insecure-requests; frame-ancestors 'none'"
	Cross-Origin-Opener-Policy-Report-Only = 'unsafe-none; report-to="default"'
	Cross-Origin-Opener-Policy = 'unsafe-none; report-to="default"'
	Cross-Origin-Embedder-Policy-Report-Only = 'unsafe-none; report-to="default"'
	Cross-Origin-Embedder-Policy = 'unsafe-none; report-to="default"'
	Cross-Origin-Resource-Policy = "cross-origin"
	Server = "simeononsecurity"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, immutable, s-max-age=604800, max-age=31536000"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"
	[plugins.inputs]
	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "https://cybersentinels.org"
	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"
	# Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
	providers = [
		"google",
		"yandex"
	]


## REDIRECTS
[[redirects]]
from = "/discord"
to = "https://discord.gg/CYVe2CyrXk"
status = 301
force = true

[[redirects]]
from = "/discord/"
to = "https://discord.gg/CYVe2CyrXk"
status = 301
force = true

[[redirects]]
from = "/github"
to = "https://github.com/CyberSentinels"
status = 301
force = true

[[redirects]]
from = "/github/"
to = "https://github.com/CyberSentinels"
status = 301
force = true